package constants

import "blackjack/structs"

var Deck = []structs.Card{
	{Name: "Ace", Value: 11, Suit: structs.Hearts},
	{Name: "2", Value: 2, Suit: structs.Hearts},
	{Name: "3", Value: 3, Suit: structs.Hearts},
	{Name: "4", Value: 4, Suit: structs.Hearts},
	{Name: "5", Value: 5, Suit: structs.Hearts},
	{Name: "6", Value: 6, Suit: structs.Hearts},
	{Name: "7", Value: 7, Suit: structs.Hearts},
	{Name: "8", Value: 8, Suit: structs.Hearts},
	{Name: "9", Value: 9, Suit: structs.Hearts},
	{Name: "10", Value: 10, Suit: structs.Hearts},
	{Name: "Jack", Value: 10, Suit: structs.Hearts},
	{Name: "Queen", Value: 10, Suit: structs.Hearts},
	{Name: "King", Value: 10, Suit: structs.Hearts},
	{Name: "Ace", Value: 11, Suit: structs.Diamonds},
	{Name: "2", Value: 2, Suit: structs.Diamonds},
	{Name: "3", Value: 3, Suit: structs.Diamonds},
	{Name: "4", Value: 4, Suit: structs.Diamonds},
	{Name: "5", Value: 5, Suit: structs.Diamonds},
	{Name: "6", Value: 6, Suit: structs.Diamonds},
	{Name: "7", Value: 7, Suit: structs.Diamonds},
	{Name: "8", Value: 8, Suit: structs.Diamonds},
	{Name: "9", Value: 9, Suit: structs.Diamonds},
	{Name: "10", Value: 10, Suit: structs.Diamonds},
	{Name: "Jack", Value: 10, Suit: structs.Diamonds},
	{Name: "Queen", Value: 10, Suit: structs.Diamonds},
	{Name: "King", Value: 10, Suit: structs.Diamonds},
	{Name: "Ace", Value: 11, Suit: structs.Clubs},
	{Name: "2", Value: 2, Suit: structs.Clubs},
	{Name: "3", Value: 3, Suit: structs.Clubs},
	{Name: "4", Value: 4, Suit: structs.Clubs},
	{Name: "5", Value: 5, Suit: structs.Clubs},
	{Name: "6", Value: 6, Suit: structs.Clubs},
	{Name: "7", Value: 7, Suit: structs.Clubs},
	{Name: "8", Value: 8, Suit: structs.Clubs},
	{Name: "9", Value: 9, Suit: structs.Clubs},
	{Name: "10", Value: 10, Suit: structs.Clubs},
	{Name: "Jack", Value: 10, Suit: structs.Clubs},
	{Name: "Queen", Value: 10, Suit: structs.Clubs},
	{Name: "King", Value: 10, Suit: structs.Clubs},
	{Name: "Ace", Value: 11, Suit: structs.Spades},
	{Name: "2", Value: 2, Suit: structs.Spades},
	{Name: "3", Value: 3, Suit: structs.Spades},
	{Name: "4", Value: 4, Suit: structs.Spades},
	{Name: "5", Value: 5, Suit: structs.Spades},
	{Name: "6", Value: 6, Suit: structs.Spades},
	{Name: "7", Value: 7, Suit: structs.Spades},
	{Name: "8", Value: 8, Suit: structs.Spades},
	{Name: "9", Value: 9, Suit: structs.Spades},
	{Name: "10", Value: 10, Suit: structs.Spades},
	{Name: "Jack", Value: 10, Suit: structs.Spades},
	{Name: "Queen", Value: 10, Suit: structs.Spades},
	{Name: "King", Value: 10, Suit: structs.Spades},
}
